
id_map = {
"HEALTHBONUS": "health",
"HEALTHREGENRAW": "raw_health_regen",
"HEALTHREGEN": "%_health_regen",
"MANAREGEN": "mana_regen",
"LIFESTEAL": "life_steal",
"MANASTEAL": "mana_steal",
"XPBONUS": "xp_bonus",
"LOOTBONUS": "loot_bonus",
"LOOTQUALITY": "loot_quality",
"EMERALDSTEALING": "stealing",
"SOULPOINTS": "soul_point_regen",
"THORNS": "thorns",
"REFLECTION": "reflection",
"POISON": "poison",
"EXPLODING": "exploding",
"STRENGTHPOINTS": "strength",
"DEXTERITYPOINTS": "dexterity",
"INTELLIGENCEPOINTS": "intelligence",
"DEFENSEPOINTS": "defense",
"AGILITYPOINTS": "agility",
"SPEED": "walk_speed",
"ATTACKSPEED": "attack_speed",
"DAMAGEBONUS": "%_melee_damage",
"DAMAGEBONUSRAW": "raw_melee_damage",
"SPELLDAMAGE": "%_spell_damage",
"SPELLDAMAGERAW": "raw_spell_damage",
"EARTHDAMAGEBONUS": "earth_damage",
"THUNDERDAMAGEBONUS": "thunder_damage",
"WATERDAMAGEBONUS": "water_damage",
"FIREDAMAGEBONUS": "fire_damage",
"AIRDAMAGEBONUS": "air_damage",
"EARTHDEFENSE": "earth_defense",
"THUNDERDEFENSE": "thunder_defense",
"WATERDEFENSE": "water_defense",
"FIREDEFENSE": "fire_defense",
"AIRDEFENSE": "air_defense",
"SPRINTREGEN": "sprint_regen",

"durabilityModifier": "durability",
"strengthRequirement": "strength_min",
"dexterityRequirement": "dexterity_min",
"intelligenceRequirement": "intelligence_min",
"defenceRequirement": "defence_min",
"agilityRequirement": "agility_min",

"duration": "duration",
"charges": "charges"
}